nelmio_api_doc:
    documentation:
        info:
            title: Home management API
            description: An app to manage your daily
            version: 1.0.0
        paths:
            /api/login_check:
                post:
                    tags:
                        - Security
                    sumarry: Authentication
                parameters:
                    - in: body
                      name: body
                      required: true
                      schema:
                          $ref: "#/definitions/AuthenticationInput"
            /api/token/refresh:
                post:
                    tags:
                        - Security
                    sumarry: Refresh token authentication
                parameters:
                    - in: body
                      name: body
                      required: true
                      schema:
                          $ref: "#/definitions/RefreshTokenInput"
            /api/logout:
                post:
                    tags:
                        - Security
                    sumarry: Allow user to logout from api & remove refresh token
                parameters:
                    - in: body
                      name: body
                      required: true
                      schema:
                          $ref: "#/definitions/LogoutInput"
        definitions:
            LogoutInput:
                type: object
                properties:
                    refreshToken:
                        type: string
                        required: true
            RefreshTokenInput:
                type: object
                properties:
                    refresh_token:
                        type: string
                        required: true
            AuthenticationInput:
                type: object
                properties:
                    username:
                        type: string
                        required: true
                    password:
                        type: string
                        required: true
            ContactRequestInput:
                type: object
                properties:
                    firstname:
                        type: string
                        required: true
                    lastname:
                        type: string
                        required: true
                    email:
                        type: string
                        required: true
                    subject:
                        type: string
                        required: true
                    message:
                        type: string
                        required: true
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc

